// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuONgWFNa2C0fvk1JrkfJo3kue4wbtnhc',
    appId: '1:1009982600478:web:cfefc660ad60e904fb450f',
    messagingSenderId: '1009982600478',
    projectId: 'utsproject-99f50',
    authDomain: 'utsproject-99f50.firebaseapp.com',
    databaseURL: 'https://utsproject-99f50-default-rtdb.firebaseio.com',
    storageBucket: 'utsproject-99f50.appspot.com',
    measurementId: 'G-HYV87SHREB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8tBX2wI43DugTM7t5YXNtzAXAf5BF9og',
    appId: '1:1009982600478:android:4f155ccdfb787baafb450f',
    messagingSenderId: '1009982600478',
    projectId: 'utsproject-99f50',
    databaseURL: 'https://utsproject-99f50-default-rtdb.firebaseio.com',
    storageBucket: 'utsproject-99f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkug8Vye724Piyvmu2qpoR4eOBnyyYJ1A',
    appId: '1:1009982600478:ios:4b320617e11e1c84fb450f',
    messagingSenderId: '1009982600478',
    projectId: 'utsproject-99f50',
    databaseURL: 'https://utsproject-99f50-default-rtdb.firebaseio.com',
    storageBucket: 'utsproject-99f50.appspot.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkug8Vye724Piyvmu2qpoR4eOBnyyYJ1A',
    appId: '1:1009982600478:ios:4b320617e11e1c84fb450f',
    messagingSenderId: '1009982600478',
    projectId: 'utsproject-99f50',
    databaseURL: 'https://utsproject-99f50-default-rtdb.firebaseio.com',
    storageBucket: 'utsproject-99f50.appspot.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuONgWFNa2C0fvk1JrkfJo3kue4wbtnhc',
    appId: '1:1009982600478:web:4b8f798464905bf6fb450f',
    messagingSenderId: '1009982600478',
    projectId: 'utsproject-99f50',
    authDomain: 'utsproject-99f50.firebaseapp.com',
    databaseURL: 'https://utsproject-99f50-default-rtdb.firebaseio.com',
    storageBucket: 'utsproject-99f50.appspot.com',
    measurementId: 'G-EKZ2PPY8Y1',
  );
}
